In [1]:
import pandas as pd 
import numpy as np  
import matplotlib.pyplot as plt  
import seaborn as sns

%matplotlib inline

In [2]:
Outpatient_Hospital_df = pd.read_csv('../notebooks/Provider_Outpatient_Hospital_Charge_Data_by_APC__CY2017 (1).csv')

In [5]:
Outpatient_Hospital_df.head(5)

,Provider_ID,Provider_Name,Provider_Street_Address,Provider_City,Provider_State,Provider_Zip_Code,Provider_HRR,APC,APC_Desc,Beneficiaries,CAPC_Services,Average_Total_Submitted_Charges,Average_Medicare_Allowed_Amount,Average_Medicare_Payment_Amount,Outlier_Services,Average_Medicare_Outlier_Amount
0,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5072,Level 2 Excision/ Biopsy/ Incision and Drainage,249.0,259,9575.01,1038.45,826.28,NaN,NaN
1,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5073,Level 3 Excision/ Biopsy/ Incision and Drainage,52.0,53,12578.28,1792.60,1423.25,NaN,NaN
2,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5091,Level 1 Breast/Lymphatic Surgery and Related P...,26.0,27,11337.61,2113.58,1683.99,0.0,0.0
3,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5092,Level 2 Breast/Lymphatic Surgery and Related P...,23.0,23,17116.16,3737.14,2977.55,0.0,0.0
4,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5112,Level 2 Musculoskeletal Procedures,17.0,17,7382.73,1029.46,820.21,0.0,0.0

In [6]:
Outpatient_Hospital_df.tail(5)

,Provider_ID,Provider_Name,Provider_Street_Address,Provider_City,Provider_State,Provider_Zip_Code,Provider_HRR,APC,APC_Desc,Beneficiaries,CAPC_Services,Average_Total_Submitted_Charges,Average_Medicare_Allowed_Amount,Average_Medicare_Payment_Amount,Outlier_Services,Average_Medicare_Outlier_Amount
61774,670122,Houston Methodist The Woodlands Hospital,17201 Interstate 45 South,The Woodlands,TX,77385,TX - Houston,5361,Level 1 Laparoscopy and Related Services,18.0,18,54778.81,3866.82,3044.48,13.0,1623.73
61775,670122,Houston Methodist The Woodlands Hospital,17201 Interstate 45 South,The Woodlands,TX,77385,TX - Houston,5373,Level 3 Urology and Related Services,11.0,11,28237.56,1469.87,1147.78,NaN,NaN
61776,670122,Houston Methodist The Woodlands Hospital,17201 Interstate 45 South,The Woodlands,TX,77385,TX - Houston,5375,Level 5 Urology and Related Services,20.0,21,35109.68,3356.89,2674.59,NaN,NaN
61777,670122,Houston Methodist The Woodlands Hospital,17201 Interstate 45 South,The Woodlands,TX,77385,TX - Houston,5431,Level 1 Nerve Procedures,NaN,12,25194.96,1506.38,1200.20,NaN,NaN
61778,670122,Houston Methodist The Woodlands Hospital,17201 Interstate 45 South,The Woodlands,TX,77385,TX - Houston,8011,Comprehensive Observation Services,156.0,165,26580.47,2141.54,1706.27,40.0,1705.11