In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
ZIP_to_CBSA = pd.read_excel('CBSA_ZIP_032020.xlsx')

In [3]:
ZIP_to_CBSA.rename(columns = {'ZIP':'zip'}, inplace = True)

In [4]:
ZIP_to_CBSA.head()

    CBSA    zip  RES_RATIO  BUS_RATIO  OTH_RATIO  TOT_RATIO
0  10100  57445   0.044115   0.016156   0.037037   0.041101
1  10100  57456   0.000046   0.000000   0.000000   0.000039
2  10100  57441   0.014690   0.003401   0.000639   0.012785
3  10100  57474   0.005792   0.003401   0.001277   0.005295
4  10100  57401   0.751576   0.788265   0.933589   0.766139

In [5]:
Hospital_Outpatient = pd.read_excel('MUP_OHP_R19_P04_V10_D17_APC_Provider.xlsx',header=5)

In [6]:
Hospital_Outpatient

,Provider ID,Provider Name,Provider Street Address,Provider City,Provider\nState,Provider\nZip Code,Provider\nHospital Referral Region\n(HRR),APC,APC\nDescription,Beneficiaries,Comprehensive APC\nServices,Average\nEstimated\nTotal\nSubmitted\nCharges,Average\nMedicare\nAllowed\nAmount,Average\nMedicare\nPayment\nAmount,Outlier\nComprehensive\nAPC\nServices,Average\nMedicare\nOutlier\nAmount
0,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5072,Level 2 Excision/ Biopsy/ Incision and Drainage,249.0,259,9575.005714,1038.454672,826.277954,NaN,NaN
1,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5073,Level 3 Excision/ Biopsy/ Incision and Drainage,52.0,53,12578.280189,1792.596792,1423.246792,NaN,NaN
2,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5091,Level 1 Breast/Lymphatic Surgery and Related P...,26.0,27,11337.608889,2113.580000,1683.990000,0.0,0.000000
3,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5092,Level 2 Breast/Lymphatic Surgery and Related P...,23.0,23,17116.158261,3737.140000,2977.550000,0.0,0.000000
4,10001,Southeast Alabama Medical Center,1108 Ross Clark Circle,Dothan,AL,36301,AL - Dothan,5112,Level 2 Musculoskeletal Procedures,17.0,17,7382.732353,1029.460000,820.210000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61774,670122,Houston Methodist The Woodlands Hospital,17201 Interstate 45 South,The Woodlands,TX,77385,TX - Houston,5361,Level 1 Laparoscopy and Related Services,18.0,18,54778.807778,3866.822778,3044.482778,13.0,1623.728077
61775,670122,Houston Methodist The Woodlands Hospital,17201 Interstate 45 South,The Woodlands,TX,77385,TX - Houston,5373,Level 3 Urology and Related Services,11.0,11,28237.564545,1469.871818,1147.781818,NaN,NaN
61776,670122,Houston Methodist The Woodlands Hospital,17201 Interstate 45 South,The Woodlands,TX,77385,TX - Houston,5375,Level 5 Urology and Related Services,20.0,21,35109.678095,3356.890000,2674.590000,NaN,NaN
61777,670122,Houston Methodist The Woodlands Hospital,17201 Interstate 45 South,The Woodlands,TX,77385,TX - Houston,5431,Level 1 Nerve Procedures,NaN,12,25194.958333,1506.380000,1200.200000,NaN,NaN
61778,670122,Houston Methodist The Woodlands Hospital,17201 Interstate 45 South,The Woodlands,TX,77385,TX - Houston,8011,Comprehensive Observation Services,156.0,165,26580.472485,2141.540000,1706.270000,40.0,1705.106900

In [7]:
APC_to_CPT_HPCS = pd.read_excel('2020_january_web_addendum_b.12312019.xlsx', header = 2)

In [8]:
APC_to_CPT_HPCS

,HCPCS Code,Short Descriptor,SI,APC,Relative Weight,Payment Rate,National Unadjusted Copayment,Minimum Unadjusted Copayment,"Note: Actual copayments would be lower due to the cap on copayments at the Inpatient Deductible of $1,408.00",* Indicates a Change
0,00100,Anesth salivary gland,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,00102,Anesth repair of cleft lip,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,00103,Anesth blepharoplasty,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,00104,Anesth electroshock,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00120,Anesth ear surgery,N,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
16623,V5299,Hearing service,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16624,V5336,Repair communication device,E1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16625,V5362,Speech screening,E1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16626,V5363,Language screening,E1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16627,V5364,Dysphagia screening,E1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
phys_other_payments = pd.read_csv('Medicare_Provider_Util_Payment_PUF_CY2017.txt', sep='\t',low_memory=False)

In [10]:
phys_other_payments = phys_other_payments.drop(phys_other_payments.index[0])

In [11]:
phys_other_payments.rename(columns={'nppes_provider_last_org_name':'provider_last_org_name',
                          'nppes_provider_first_name':'provider_first_name',
                          'nppes_provider_mi':'provider_mi',
                          'nppes_credentials':'credentials',
                          'nppes_provider_gender ':'provider_gender',
                          'nppes_entity_code':'entity_code',
                          'nppes_provider_street1':'provider_street1',
                          'nppes_provider_street2':'provider_street2',
                          'nppes_provider_city':'provider_city',
                          'nppes_provider_zip':'zip',
                          'nppes_provider_state':'provider_state',
                          'nppes_provider_country':'country'},inplace=True)

In [12]:
phys_other_payments['zip'] = phys_other_payments['zip'].str[:5]

In [13]:
phys_other_payments = phys_other_payments[phys_other_payments.country == 'US']

In [14]:
phys_other_payments['zip'] = pd.to_numeric(phys_other_payments['zip'])

In [15]:
phys_other_payments['zip'] = phys_other_payments['zip'].apply(lambda x: '{0:0>5}'.format(x))

In [16]:
phys_other_payments.head()

,npi,provider_last_org_name,provider_first_name,provider_mi,credentials,nppes_provider_gender,entity_code,provider_street1,provider_street2,provider_city,zip,provider_state,country,provider_type,medicare_participation_indicator,place_of_service,hcpcs_code,hcpcs_description,hcpcs_drug_indicator,line_srvc_cnt,bene_unique_cnt,bene_day_srvc_cnt,average_Medicare_allowed_amt,average_submitted_chrg_amt,average_Medicare_payment_amt,average_Medicare_standard_amt
1,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,21502,MD,US,Internal Medicine,Y,F,99217,Hospital observation care discharge,N,100.0,96.0,100.0,73.398800,325.780000,56.827200,57.492400
2,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,21502,MD,US,Internal Medicine,Y,F,99218,Hospital observation care typically 30 minutes,N,26.0,25.0,26.0,100.080000,449.000000,78.460000,79.306154
3,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,21502,MD,US,Internal Medicine,Y,F,99219,Hospital observation care typically 50 minutes,N,52.0,51.0,52.0,136.380000,614.000000,102.807692,103.895385
4,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,21502,MD,US,Internal Medicine,Y,F,99220,Hospital observation care typically 70 minutes...,N,59.0,59.0,59.0,190.363729,755.932203,141.293559,142.865763
5,1003000126,ENKESHAFI,ARDALAN,NaN,M.D.,M,I,900 SETON DR,NaN,CUMBERLAND,21502,MD,US,Internal Medicine,Y,F,99221,"Initial hospital inpatient care, typically 30 ...",N,16.0,16.0,16.0,101.680000,462.812500,79.710000,80.750000

In [17]:
ZIP_to_CBSA.zip.astype(object)

0        57445
1        57456
2        57441
3        57474
4        57401
         ...
47410    95922
47411    95920
47412    95665
47413    95689
47414    95254
Name: zip, Length: 47415, dtype: object